library(stringr)
pp<-readClipboard()
ppp<-noquote(pp)
df0<-as.data.frame(ppp,sep=",")
df<-data.frame(str_split_fixed(df0$pp,",",3))
colnames(df)<-c("date","time","docs")
head(df)
df1<-data.frame(date=as.Date(df$date),docs=as.numeric(df$docs))
str(df1)
df2<-as.data.frame(tapply(df1$docs,df1$date,sum))
str(df2)
months(df1$date)
quarters(df1$date)
as.yearqtr(df1$date)
tapply(df1$docs,months(df1$date),mean)
sum(df1$docs)
df1$Month_Yr <- format(as.Date(df$date), "%Y-%m")
df2<-as.data.frame(tapply(df1$docs,df1$Month_Yr,sum))
str(df2)
colnames(df2)=c("x")
str_split(df2$x," ")
################
gsub("[()]","",xx)   # square bracket to treat as characters
